"""Prove what the built image is, and what is actually inside it.

Two claims were being made about the release image without being checked, and both
were false in CI:

`LOTUS_CI_PIPELINE_ID` reached the image as `local`, because the workflow ran
`make docker-build` without overriding the Makefile default. `local` is the value that
means "someone built this on a workstation", so every CI image asserted it was not a
CI image. `git_branch` reached it as `HEAD`, because `actions/checkout` leaves a
detached HEAD and `git rev-parse --abbrev-ref HEAD` answers literally.

The dependency SBOM was generated by running `cyclonedx_py environment` on the
*runner's* Python. That inventories the environment `make install` created --
including the dev extras and the SBOM tool itself -- and never opens the image. It
produced a plausible component list for software that is not what ships.

So both are verified against the running artifact rather than against the build
command: provenance by asking the container's own `/version`, and the inventory by
generating it inside an ephemeral container started from the image.

Scanner tooling stays out of the shipped runtime. The scan container is started with
`--rm`, the tool is installed into that instance only, and nothing is committed back
to the image.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
import tomllib
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[1]
CONTAINER_PORT = "8310"
SBOM_TOOL_REQUIREMENT = "cyclonedx-bom==7.3.1"

# A digest does not exist before push, so this is the truthful value rather than a
# missing one. Verified rather than ignored: replacing it with a guess is the failure
# this field exists to prevent.
DIGEST_BEFORE_PUSH = "unavailable-before-push"


def _run(command: list[str], **kwargs: Any) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, capture_output=True, text=True, **kwargs)


def _image_id(image_ref: str) -> str:
    completed = _run(["docker", "image", "inspect", "--format", "{{.Id}}", image_ref])
    if completed.returncode != 0:
        raise SystemExit(f"cannot inspect image {image_ref}: {completed.stderr.strip()}")
    return completed.stdout.strip()


def _wait_for_version(url: str, attempts: int = 60) -> dict[str, Any]:
    """Poll `/version` until the service answers, or refuse.

    A container that never becomes ready must not be reported as a provenance
    mismatch: the two failures need different operator actions, so the timeout says
    so in its own words.
    """

    last_error = ""
    for _ in range(attempts):
        try:
            with urllib.request.urlopen(url, timeout=2) as response:
                if response.status == 200:
                    return json.loads(response.read().decode("utf-8"))
                last_error = f"HTTP {response.status}"
        except (urllib.error.URLError, OSError, TimeoutError) as error:
            last_error = str(error)
        time.sleep(1)
    raise SystemExit(f"the container never served {url}; last error: {last_error}")


def verify_runtime_provenance(args: argparse.Namespace) -> int:
    container = f"lotus-render-provenance-{args.expected_ci_run_id}"
    _run(["docker", "rm", "-f", container])
    started = _run(
        [
            "docker",
            "run",
            "-d",
            "--name",
            container,
            "-p",
            f"127.0.0.1:0:{CONTAINER_PORT}",
            args.image_ref,
        ]
    )
    if started.returncode != 0:
        raise SystemExit(f"could not start {args.image_ref}: {started.stderr.strip()}")

    try:
        published = _run(["docker", "port", container, CONTAINER_PORT])
        if published.returncode != 0 or not published.stdout.strip():
            raise SystemExit(f"no published port for {container}: {published.stderr.strip()}")
        host_port = published.stdout.strip().splitlines()[0].rsplit(":", 1)[1]
        version = _wait_for_version(f"http://127.0.0.1:{host_port}/version")
    finally:
        _run(["docker", "rm", "-f", container])

    expected = {
        "service_name": "lotus-render",
        "git_commit_sha": args.expected_commit,
        "git_branch": args.expected_branch,
        "ci_pipeline_run_id": args.expected_ci_run_id,
        "image_digest": DIGEST_BEFORE_PUSH,
    }
    mismatches = [
        f"{field}: image reports {version.get(field)!r}, expected {value!r}"
        for field, value in expected.items()
        if version.get(field) != value
    ]

    evidence = {
        "image_ref": args.image_ref,
        "image_id": _image_id(args.image_ref),
        "reported_version": version,
        "expected": expected,
        "mismatches": mismatches,
        "verified_through": "GET /version on a container started from the built image",
    }
    if args.output:
        Path(args.output).parent.mkdir(parents=True, exist_ok=True)
        Path(args.output).write_text(json.dumps(evidence, indent=2), encoding="utf-8")

    if mismatches:
        print("Image provenance verification FAILED.")
        for mismatch in mismatches:
            print(f"- {mismatch}")
        return 1

    print(
        "Image provenance verified against the running container: "
        f"commit={version['git_commit_sha']} branch={version['git_branch']} "
        f"ci_run={version['ci_pipeline_run_id']} digest={version['image_digest']}"
    )
    return 0


def _declared_dependencies() -> tuple[set[str], set[str]]:
    """Runtime and dev-only distribution names, normalised, from `pyproject.toml`."""

    project = tomllib.loads((REPO_ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]

    def names(requirements: list[str]) -> set[str]:
        parsed = set()
        for requirement in requirements:
            name = requirement.split("==")[0].split(">")[0].split("[")[0].strip()
            parsed.add(name.lower().replace("_", "-"))
        return parsed

    runtime = names(project["dependencies"])
    dev = names(project["optional-dependencies"]["dev"]) - runtime
    return runtime, dev


def runtime_sbom(args: argparse.Namespace) -> int:
    image_id = _image_id(args.image_ref)

    # `--user root` so the tool can install into this instance; `--rm` so the instance
    # is discarded. The shipped image runs as `lotus` and never contains the tool.
    generated = _run(
        [
            "docker",
            "run",
            "--rm",
            "--user",
            "root",
            "--entrypoint",
            "sh",
            args.image_ref,
            "-c",
            f"pip install --no-cache-dir --quiet {SBOM_TOOL_REQUIREMENT} 1>&2 && "
            "python -m cyclonedx_py environment --output-format JSON",
        ]
    )
    if generated.returncode != 0:
        raise SystemExit(
            f"could not generate an SBOM inside {args.image_ref} "
            f"(exit {generated.returncode}): {generated.stderr.strip()[-2000:]}"
        )

    try:
        sbom = json.loads(generated.stdout)
    except json.JSONDecodeError as error:
        raise SystemExit(f"the scan container did not emit JSON: {error}") from error

    present = {
        str(component.get("name", "")).lower().replace("_", "-")
        for component in sbom.get("components", [])
    }
    runtime_dependencies, dev_only = _declared_dependencies()

    failures: list[str] = []
    missing = sorted(runtime_dependencies - present)
    if missing:
        failures.append(
            f"declared runtime dependencies absent from the image inventory: {', '.join(missing)}"
        )
    # The discriminating half. The runner's environment holds the dev extras, so an
    # inventory taken there contains pytest and ruff; the image installs `.` only and
    # cannot. Without this, an SBOM regenerated on the runner would still satisfy the
    # check above and the original defect would return unnoticed.
    leaked = sorted(dev_only & present)
    if leaked:
        failures.append(
            "dev-only distributions present, so this inventory did not come from the "
            f"shipped runtime: {', '.join(leaked)}"
        )
    if not present:
        failures.append("the inventory lists no components at all")

    # Bind the document to the artifact it describes. Without this the file is an
    # inventory of nothing in particular, and a stale copy cannot be told apart from a
    # current one.
    sbom.setdefault("metadata", {}).setdefault("properties", []).extend(
        [
            {"name": "lotus:image-ref", "value": args.image_ref},
            {"name": "lotus:image-id", "value": image_id},
            {"name": "lotus:generated-from", "value": "ephemeral container of the built image"},
        ]
    )

    coverage = {
        "python_distributions": True,
        # `cyclonedx_py environment` reads installed Python distributions. Debian
        # packages from the `python:3.12-slim` base are outside what it can see.
        "operating_system_packages": False,
        # Typst is a binary copied from `ghcr.io/typst/typst`, not a pip
        # distribution, so it cannot appear in a Python-environment inventory. It is
        # recorded here by its pinned source rather than left to be inferred absent.
        "typst_binary": False,
        "typst_source": _typst_pin(),
    }

    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(json.dumps(sbom, indent=2), encoding="utf-8")
    if args.evidence:
        Path(args.evidence).parent.mkdir(parents=True, exist_ok=True)
        Path(args.evidence).write_text(
            json.dumps(
                {
                    "image_ref": args.image_ref,
                    "image_id": image_id,
                    "component_count": len(present),
                    "declared_runtime_dependencies_present": sorted(runtime_dependencies),
                    "dev_only_distributions_present": leaked,
                    "coverage": coverage,
                    "tool": SBOM_TOOL_REQUIREMENT,
                    "failures": failures,
                },
                indent=2,
            ),
            encoding="utf-8",
        )

    if failures:
        print("Runtime SBOM gate FAILED.")
        for failure in failures:
            print(f"- {failure}")
        return 1

    print(
        f"Runtime SBOM generated from {args.image_ref} ({image_id[:19]}): "
        f"{len(present)} python distributions, all {len(runtime_dependencies)} declared runtime "
        f"dependencies present, no dev-only distributions. "
        "OS packages and the Typst binary are NOT covered by this inventory."
    )
    return 0


def _typst_pin() -> str:
    """The Typst image the binary is copied from, read rather than restated."""

    for line in (REPO_ROOT / "Dockerfile").read_text(encoding="utf-8").splitlines():
        if line.startswith("FROM") and "typst" in line:
            return line.split()[1]
    return "unknown"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    subcommands = parser.add_subparsers(dest="command", required=True)

    provenance = subcommands.add_parser("verify-runtime-provenance")
    provenance.add_argument("--image-ref", required=True)
    provenance.add_argument("--expected-commit", required=True)
    provenance.add_argument("--expected-branch", required=True)
    provenance.add_argument("--expected-ci-run-id", required=True)
    provenance.add_argument("--output")
    provenance.set_defaults(handler=verify_runtime_provenance)

    sbom = subcommands.add_parser("runtime-sbom")
    sbom.add_argument("--image-ref", required=True)
    sbom.add_argument("--output", required=True)
    sbom.add_argument("--evidence")
    sbom.set_defaults(handler=runtime_sbom)

    args = parser.parse_args()
    return int(args.handler(args))


if __name__ == "__main__":
    sys.exit(main())
